server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-consumer-group
      auto-offset-reset: earliest
      concurrency: 5
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: RECORD
    topic:
      name: log-topic

  redis:
    host: localhost
    port: 6379
    ttl: 1

logging:
  level:
    root: INFO
    com.kafein: DEBUG
    org.springframework: WARN
  file:
    name: logs/application.log